language: node_js
node_js:
- 0.12.7
before_install:
- openssl aes-256-cbc -K $encrypted_f570f65b1408_key -iv $encrypted_f570f65b1408_iv
  -in .travis/deploy_rsa.enc -out ~/.ssh/deploy_rsa -d
- chmod 600 ~/.ssh/deploy_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/deploy_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "Peter Chung"
- git config --global user.email "touhonoob@gmail.com"
install:
- bundle install
- npm install
script:
- gulp
after_script:
- ./.travis/deploy.sh
branches:
  only:
    - master
